### ISSUE TITLE
Allow the user to select how many days of logfiles to keep

### ISSUE THREAD

**Issue by JHGrove3** [dappnode/DAppNodePackage-ssv-generic#5]
**Is your feature request related to a problem? Please describe.**

Lido requires its SSV operators to have 28 days of logfiles to help with debugging and identify block proposal problems.
This is normally set by adding:

  LogFileBackups: 28

to the config.yaml file

**Describe the solution you'd like**

Please create a user setting where the user can indicate how many days of logs to keep.

Alternatively, allow the user to add a field in the "EXTRA_OPTS" config category that specifies the days to keep.

**Describe alternatives you've considered**

I've tried manually editing the package by SSH, but it loses my edits when the package restarts

**Additional context**

Have spoken with Diego about this change

**Comment by dappnodedev** [comment]
@JHGrove3 I have already included this feature in the package. The latest release here: https://github.com/dappnode/DAppNodePackage-ssv-generic/releases will include that change

**Comment by dappnodedev** [comment]
Thanks for the detailed explanation. You will find a new env called `LOG_FILE_BACKUPS` in the package config, where you can edit this setting
